# Generated by Django 4.0.4 on 2022-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug1',
            field=models.SlugField(default=''),
        ),
    ]
